/* eslint-disable */
// AUTO-GENERATED — 运行 npm run sync:harness 重新生成；请勿手改。
export const harnessTailwindExtend = {
  "spacing": {
    "business-table-cell-y-compact": "0.5rem",
    "business-table-cell-y-default": "0.75rem",
    "business-table-cell-y-comfortable": "1rem"
  },
  "colors": {},
  "borderRadius": {}
} as const;

/** 来自 schema enumMap / baselineTokens，供 Tailwind JIT 拣选 */
export const harnessSafelist: string[] = [
  "accent-primary",
  "bg-background",
  "bg-destructive",
  "bg-primary",
  "bg-secondary",
  "bg-transparent",
  "border",
  "border-collapse",
  "border-input",
  "border-transparent",
  "caption-bottom",
  "disabled:opacity-50",
  "disabled:pointer-events-none",
  "even:bg-muted/40",
  "flex",
  "focus-visible:outline-none",
  "focus-visible:ring-1",
  "focus-visible:ring-ring",
  "font-medium",
  "font-semibold",
  "h-10",
  "h-4",
  "h-8",
  "h-9",
  "hover:bg-accent",
  "hover:bg-destructive/90",
  "hover:bg-primary/90",
  "hover:bg-secondary/80",
  "hover:text-accent-foreground",
  "hover:underline",
  "inline-flex",
  "items-center",
  "justify-center",
  "min-w-0",
  "px-2.5",
  "px-3",
  "px-4",
  "px-8",
  "py-0.5",
  "py-1",
  "py-2",
  "py-business-table-cell-y-comfortable",
  "py-business-table-cell-y-compact",
  "py-business-table-cell-y-default",
  "rounded",
  "rounded-md",
  "shadow",
  "shadow-sm",
  "shrink-0",
  "text-destructive-foreground",
  "text-foreground",
  "text-primary",
  "text-primary-foreground",
  "text-secondary-foreground",
  "text-sm",
  "text-xs",
  "transition-colors",
  "underline-offset-4",
  "w-4",
  "w-9",
  "w-full"
];
