/* eslint-disable */
// AUTO-GENERATED — 运行 npm run sync:harness 重新生成；请勿手改。
export const harnessTailwindExtend = {
  "spacing": {
    "business-table-cell-y-compact": "0.5rem",
    "business-table-cell-y-default": "0.75rem",
    "business-table-cell-y-comfortable": "1rem"
  },
  "colors": {},
  "borderRadius": {}
} as const;

/** 来自 schema enumMap / baselineTokens，供 Tailwind JIT 拣选 */
export const harnessSafelist: string[] = [
  "absolute",
  "accent-primary",
  "animate-pulse",
  "appearance-none",
  "aspect-square",
  "backdrop:bg-black/40",
  "bg-background",
  "bg-border",
  "bg-card",
  "bg-destructive",
  "bg-muted",
  "bg-popover",
  "bg-primary",
  "bg-secondary",
  "bg-transparent",
  "border",
  "border-border",
  "border-collapse",
  "border-destructive/50",
  "border-input",
  "border-transparent",
  "caption-bottom",
  "cursor-pointer",
  "disabled:cursor-not-allowed",
  "disabled:opacity-50",
  "disabled:pointer-events-none",
  "even:bg-muted/40",
  "fixed",
  "flex",
  "focus-visible:outline-none",
  "focus-visible:ring-1",
  "focus-visible:ring-ring",
  "font-medium",
  "font-semibold",
  "grid",
  "h-10",
  "h-11",
  "h-2",
  "h-4",
  "h-5",
  "h-7",
  "h-9",
  "hover:bg-accent",
  "hover:bg-destructive/90",
  "hover:bg-primary/90",
  "hover:bg-secondary/80",
  "hover:text-accent-foreground",
  "hover:underline",
  "inline-flex",
  "inset-0",
  "items-center",
  "justify-center",
  "leading-none",
  "max-w-lg",
  "min-h-[80px]",
  "min-w-0",
  "min-w-[10rem]",
  "min-w-[12rem]",
  "overflow-auto",
  "overflow-hidden",
  "overscroll-contain",
  "p-0",
  "peer-checked:bg-primary",
  "peer-disabled:cursor-not-allowed",
  "peer-disabled:opacity-70",
  "placeholder:text-muted-foreground",
  "px-2",
  "px-2.5",
  "px-3",
  "px-4",
  "px-8",
  "py-0",
  "py-0.5",
  "py-1",
  "py-1.5",
  "py-2",
  "py-business-table-cell-y-comfortable",
  "py-business-table-cell-y-compact",
  "py-business-table-cell-y-default",
  "relative",
  "ring-offset-background",
  "rounded",
  "rounded-full",
  "rounded-lg",
  "rounded-md",
  "rounded-xl",
  "shadow",
  "shadow-inner",
  "shadow-lg",
  "shadow-md",
  "shadow-sm",
  "shrink-0",
  "size-9",
  "text-card-foreground",
  "text-destructive",
  "text-destructive-foreground",
  "text-foreground",
  "text-muted-foreground",
  "text-popover-foreground",
  "text-primary",
  "text-primary-foreground",
  "text-secondary-foreground",
  "text-sm",
  "text-xs",
  "transition-all",
  "transition-colors",
  "underline-offset-4",
  "w-10",
  "w-4",
  "w-9",
  "w-full",
  "whitespace-nowrap",
  "z-50"
];
